### ISSUE TITLE
PFS wont start: Err "No module named 'wx.svg'

### ISSUE THREAD

**Issue by jf-simon** [PhotoFilmStrip/PFS#101]
I love PFS, but 
pfs wont start: Err "No module named 'wx.svg'"

[simon@hope PFS-4.0.0]$ photofilmstrip
Traceback (most recent call last):
  File "/usr/local/bin/photofilmstrip", line 8, in <module>
    main()
  File "/usr/local/lib/python3.10/site-packages/photofilmstrip/GUI.py", line 51, in main
    guiApp.Start()
  File "/usr/local/lib/python3.10/site-packages/photofilmstrip/AppMixin.py", line 55, in Start
    return self._OnStart()
  File "/usr/local/lib/python3.10/site-packages/photofilmstrip/GUI.py", line 28, in _OnStart
    from photofilmstrip.gui.PhotoFilmStripApp import PhotoFilmStripApp
  File "/usr/local/lib/python3.10/site-packages/photofilmstrip/gui/PhotoFilmStripApp.py", line 15, in <module>
    from photofilmstrip.gui.ArtProvider  import ArtProvider
  File "/usr/local/lib/python3.10/site-packages/photofilmstrip/gui/ArtProvider.py", line 12, in <module>
    import wx.svg
ModuleNotFoundError: No module named 'wx.svg'

i'm using fedora 36
tried building from source and the 4.0.0 release.

Any tips?

Greetings Simon

**Comment by jensgoe** [comment]
Thanks. If you want to start from source you need wxPython4.1. Sadly that's not included in official package repository. Either you compile it wxPython4.1 from sources as well or start PFS from source branch wxPy-4.0.x. It is up to date to master branch except the wx.svg stuff.
