### ISSUE TITLE
Crash upon program startup [Py3.8]

### ISSUE THREAD

**Issue by acxz** [PhotoFilmStrip/PFS#63]
When trying to run this program I get the following error:
```
Traceback (most recent call last):
  File "/usr/bin/photofilmstrip", line 8, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/photofilmstrip/GUI.py", line 45, in main
    guiApp.Start()
  File "/usr/lib/python3.8/site-packages/photofilmstrip/AppMixin.py", line 45, in Start
    self.InitI18N()
  File "/usr/lib/python3.8/site-packages/photofilmstrip/AppMixin.py", line 31, in InitI18N
    ActionI18N().Execute()
  File "/usr/lib/python3.8/site-packages/photofilmstrip/action/ActionI18N.py", line 43, in Execute
    lang.install(True)
  File "/usr/lib/python3.8/gettext.py", line 352, in install
    for name in allowed & set(names):
TypeError: 'bool' object is not iterable
```
OS: ArchLinux
Python version: 3.8.1
Latest commit as of posting this: https://github.com/PhotoFilmStrip/PFS/commit/e7fbf5d9a7f0943dbff91445e566f57a6436e2ff

**Comment by acxz** [comment]
Thank you for the quick fix!
