### ISSUE TITLE
Crash upon program startup [GES/gi] [Py3.8]

### ISSUE THREAD

**Issue by acxz** [PhotoFilmStrip/PFS#65]
When trying to run this program I get the following error:
```
Traceback (most recent call last):
  File "/usr/bin/photofilmstrip", line 8, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/photofilmstrip/GUI.py", line 45, in main
    guiApp.Start()
  File "/usr/lib/python3.8/site-packages/photofilmstrip/AppMixin.py", line 46, in Start
    self.InitGStreamer()
  File "/usr/lib/python3.8/site-packages/photofilmstrip/AppMixin.py", line 37, in InitGStreamer
    gi.require_version('GES', '1.0')
  File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GES not available
```
OS: ArchLinux
Python version: 3.8.1
`python-gobject` version: 3.34.0
Latest commit as of posting this: https://github.com/PhotoFilmStrip/PFS/commit/4cf1dac58e7f1df6305479e996088c33f69990ed

**Comment by jensgoe** [comment]
i've added a new feature in the master branch that needed ges (gstreamer-editing-services). you probably need gir1.2-ges-1.0, libges-1.0-0.

**Comment by acxz** [comment]
Yep that did the trick thank you so much for your help @jensgoe !
